"""Migrate commit

Revision ID: c75f53323776
Revises: 
Create Date: 2025-03-16 01:33:42.987893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75f53323776'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('user_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_histories')
    op.drop_table('invites')
    # ### end Alembic commands ###
